[log]
level = "warn"
output = "/var/log/realm.log"

[network]
no_tcp = false
use_udp = true

[[endpoints]]
listen = "[::0]:10000"
remote = "1.1.1.1:443"
remote_transport = "tls;sni=example.com;insecure"

[[endpoints]]
listen = "[::0]:20000"
remote = "www.google.com:443"
listen_transport = "tls;servername=example.com"